### PR TITLE
Rename parser.py to yparser.py to avoid conflict with builtin module

### PR DESCRIPTION
**Pull request by yeputons**

### CODE REVIEW

**Comment by krinkinmu** [comment]
1. don't combine unrelated changes in one PR
2. to avoid collisions use import as, no point adding silly prefixes, so nack for that change.

**Comment by yeputons** [comment]
@krinkinmu 
1. Will fix and create a separate PR for shebang.
2. Collision happens when one tries to import module named exactly as builtin module: Python 3.5.2 looks for builtin modules before any others (<a href="https://docs.python.org/3/tutorial/modules.html#the-module-search-path">doc</a>). So, if `parser` is a built-in module (as it is on my system), all imports fail.

**Comment by yeputons** [comment]
@krinkinmu added more details to commit message in this PR, moved shebang change to #2

**Comment by krinkinmu** [comment]
@yeputons, ok, in this way correct thing to do would be to use relative imports, they exist exactly to solve this kind of problems, like this https://github.com/krinkinmu/yat/compare/use-relative-import

**Comment by yeputons** [comment]
@krinkinmu Unfortunately, it does not work well when running scripts with `./run.py` (<a href="http://stackoverflow.com/q/16981921/767632">stackoverflow</a>):

```
Traceback (most recent call last):
  File "run.py", line 3, in <module>
    from .parser import Parser, Scanner
SystemError: Parent module '' not loaded, cannot perform relative import
```

Quoting <a href="https://docs.python.org/3/tutorial/modules.html#intra-package-references">documentation</a>:

<blockquote>
Note that relative imports are based on the name of the current module. Since the name of the main module is always "__main__", modules intended for use as the main module of a Python application must always use absolute imports.</blockquote>

Of course, one can say that the only correct way of running this thing is `python -m run` from `yat` folder (and not any other folder) and describing that in a comment, but, imho, name clashing with built-in modules is already bad enough.

**Comment by krinkinmu** [comment]
I still disagree, there is no ambiguity here, it's quite clear that we don't want to use standard parser module here, moreover there are plenty of standard python modules, checking for clashes when there are so much of them seem just stupid.

But ok, except one detail, lets instead of prefix use separate package like this https://github.com/krinkinmu/yat/compare/use-package, but probably we need also to fix task a bit, so that students use import yat.model instead of import model in constant folder visitor.

**Comment by yeputons** [comment]
@krinkinmu Yup, `use-package` branch looks good to me, it's better. Closing this PR then.

**Pull request closed without merging**
