### PR TITLE
Add test_print() to run_smoke_tests.py

### PR DESCRIPTION
**Pull request by yeputons**
It tests that `model.Print.evaluate()`:
- Prints number on a separate line.
- Returns the number printed.

Unfortunately, it's impossible to test no.2 with a YAT program because parser does not allow `print` statement to appear inside expression.

### CODE REVIEW

**Comment by krinkinmu** [comment]
But you could put orint inside function, and call that function, so it's actually possible to test 2nd property

**Comment by yeputons** [comment]
@krinkinmu It won't test that implementation returns the exact object that was passed to `Print` (if it was a `Number`, not some expression). Not sure if that matters.

**Comment by krinkinmu** [comment]
It should, IIRC, according to the task number evaluate should return self, and if we pass number to the function that calls print, print should evaluate expression, which is just Number in our case, and return result of evaluation which in our case should be exactly same object passed to the function.

**Comment by yeputons** [comment]
@krinkinmu If it's the case, then writing a program (<a href="https://github.com/yeputons/yat/commit/6c6f9f20b04901c601cdefb82daef81055a4b06d">example</a>) won't fully check `print` statement - some implementations may want to create new `Number`, e.g.:

```
value = self.expr.evaluate(scope)
print(value)
return Number(value)
```

**Comment by krinkinmu** [comment]
It's not actually correct, since value is either Number or Function (in correct case it may only be Number), and so Number(value) is not correct, since Number takes integer as an argument. But ok, we still can write test, though not atomic:

```
def print_fun(x) {
    print x;
}
if (2 == print_fun(2)) {
    print 1;
} else {
    print 0;
}
```

**Comment by yeputons** [comment]
@krinkinmu I did not get your point about `Number` or `Function` being correct argument to `print` in YAT - I thought it should not happen in correct programs and the interpreter is free to assume that it's the case?

**Comment by krinkinmu** [comment]
What? I wrote that the only correct option is Number. But generally result of evaluate may be Function or Number. But anyway, the point is that Number(value) is incorrect, so i have doubts that someone can write something like your code above.

**Comment by yeputons** [comment]
@krinkinmu closing this as it's mostly covered by bb370c9e6d

**Pull request closed without merging**
